### ISSUE TITLE
Add additional comments for pSecurityAccountId and pLogArchiveAccountId properties

### ISSUE THREAD

**Issue by gadouryd** [aws-ia/cfn-abi-crowdstrike-fcs#55]
Section heading: Deployment steps

Documentation issue description: The **Update values of below parameters as needed** section does not include entries for pSecurityAccountId or pLogArchiveAccountId properties. These are only needed when creating a new Cloud Trail.

**Comment by ryanjpayne** [comment]
Issue has been resolved in PR#57
@kkvinjam please link this to https://github.com/aws-ia/cfn-abi-crowdstrike-fcs/pull/57 and close

**Comment by kkvinjam** [comment]
Closes #57
